export default {
  ACTIVITIES: 'activities',
  ACTIVITY_EXECUTIONS: 'activityExecutions',
  CHANNELS: 'channels',
  DATASETS: 'datasets',
  EXPERIMENTS: 'experiments',
  LIFE_ACTIVITIES: 'lifeActivities',
  MEASURES: 'measures',
  MODALITIES: 'modalities',
  PARAMETERS: 'parameters',
  PARTICIPANTS: 'participants',
  PARTICIPANT_STATES: 'participantStates',
  RECORDINGS: 'recordings',
  SCENARIOS: 'scenarios',
  SCENARIO_EXECUTIONS: 'scenarioExecutions',
  TIME_SERIES: 'timeSeries',
};
