export default {
  ACTIVITY: 'activity',
  ACTIVITY_EXECUTION: 'activityExecution',
  CHANNEL: 'channel',
  DATASET: 'dataset',
  EXPERIMENT: 'experiment',
  LIFE_ACTIVITY: 'lifeActivity',
  MEASURE: 'measure',
  MODALITY: 'modality',
  PARAMETER: 'parameter',
  PARTICIPANT: 'participant',
  PARTICIPANT_STATE: 'participantState',
  RECORDING: 'recording',
  SCENARIO: 'scenario',
  SCENARIO_EXECUTION: 'scenarioExecution',
  TIME_SERIE: 'timeSeries',
};
